services:

  ##################
  # mongodb  #
  ##################
  mongodb:
    container_name: mongodb  
    hostname: mongodb  
    image: mongo:latest      
    ports:
      - "27017:27017"       
    volumes:
      - users_volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=project
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - shared_network
    restart: always


  ##################
  # flask_app #
  ##################
  flask_app:
    container_name: flask_app
    build: .  
    ports:
      - "5000:5000"  
    volumes:
      - /app
    depends_on:
      - mongodb
    networks:
      - shared_network
    restart: always

##################
# Mongo Express  #
##################
  mongo_express:
    container_name: mongo_express
    image: mongo-express
    ports:
      - "8081:8081"  
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - shared_network
    restart: unless-stopped

networks:
  shared_network:
    driver: bridge

volumes:
  users_volume: